services:
  bibliotheque:
    build: .
    container_name: bibliotheque
    restart: unless-stopped
    ports:
      - "7000:3000"
    volumes:
      # Modifiez la partie gauche pour un dossier de votre NAS, ex :
      # /volume1/docker/bibliotheque/data:/app/data
      - ./data:/app/data
